---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lubridate)
library(ggcorrplot)
library('corrr')
source("data_processing.R")
source("496_utils.R")
game_ids <- c()
set.seed(43)
for(year in c(list.files(path="play_data"))) {
  # we always have play-by-play, but not always shift_data. thus, get info abt shift and check for matching play_data
  new_path <- paste("play_data/", year, sep="")
  new_path <- paste(new_path, "/", sep="")
  for(game in list.files(path=new_path)){
    game_ids <- c(game_ids, game)
  }
}

player_ids <- read_csv("player_data/all_seasons_rosters.csv")
schedule_info <- read_csv("./nhl_schedule.csv")
all_szns <- read_csv("combined_seasons.csv")
all_games <- read_csv("./all_games_df.csv")
all_games$yr <- substring(all_games$game_id, 1, 4)
all_games$time <- 3600 - all_games$timeLeft
all_games <- select(all_games, -c(timeLeft))
#all_games <- get_all_game_info(game_ids, player_ids)
all_games <- select(all_games, -c(timeLeft, `...1`))
```
```{r}
i <- 1
for(rankings_data in c(list.files(path="rankings_data"))) {
  new_path <- paste("rankings_data/", rankings_data, sep="")
  if(i ==1) {
    time_ranks <- read_csv(new_path)
  } else {
    time_ranks <- rbind(time_ranks, read_csv(new_path))
  }
  i <- i+1
}
time_ranks
```
```{r}

```
```{r, eval = FALSE}

blitz_win <- function(simul_plays, prev_tm1PIM) {
  prev_tm1PIM <- prev_tm1PIM
  prev_tm2PIM <- simul_plays[1,]$tm2PIM
  
  final_tm1PIM <- simul_plays[nrow(simul_plays),]$tm1PIM #+ simul_plays[1,]$tm1PIM
  final_tm2PIM <- simul_plays[nrow(simul_plays),]$tm2PIM
  
  tm1_diff <- final_tm1PIM - prev_tm1PIM
  tm2_diff <- final_tm2PIM - prev_tm2PIM
  #print(tm1_diff)
  #print(tm2_diff)
  if(tm1_diff > tm2_diff) {
    return(1)
  } else if(tm1_diff == tm2_diff) {
    return(0)
  } else {
    return(-1)
  }
}

count = 1

for(id in unique(all_games$game_id)) {
  game_df <- all_games[all_games$game_id == id,]
  yr = substring(id, 1, 4)

  row = 1
  timeSteps = 1
  running_blitz <- 0
  blitz_diff <- c()
  
  for(time in unique(game_df$timeLeft)) {
    simul_plays <- game_df[game_df$timeLeft == time, ]
    #print(simul_plays)
    
    if(nrow(simul_plays) > 1) { # potential for a "blitz"
      if(timeSteps == 1) {
        prev_PIM <- 0
      } else {
        prev_PIM <- simul_plays[timeSteps-1,]$tm1PIM
      }
      #print(sprintf("prev pim: %s", prev_PIM))
      #curr_blitz <- blitz_win(simul_plays, prev_PIM) #blitz == 1 means team 1 won the "blitz"
      #print(curr_blitz)
      #running_blitz <- running_blitz + curr_blitz
      
      timeSteps <- timeSteps + 1
    }
    
    to_add_vec <- rep(running_blitz, nrow(simul_plays))
    #print(sprintf("simultaneous plays:%s, adding %s", nrow(simul_plays), to_add_vec))
    #print(to_add_vec)
    blitz_diff <- c(blitz_diff, to_add_vec)
    row = row + nrow(simul_plays)
    #print(simul_plays)
  }

  #print(blitz_diff)
  
  #print(nrow(game_df))
  
  game_df$tm1_blitz_won <- blitz_diff
  #if(count == 1) {
    #break
  #}
  
}
```
# Original Win Probability Model Training
```{r}
gameIds <- unique(all_games$game_id)

train_games <- sample(gameIds, 0.8 * length(gameIds)) ## select 400 games for our training set

train <- all_games %>% 
  filter(game_id %in% train_games) 

test <- all_games %>% 
  filter(!game_id %in% train_games) 

mod <- glm(tm1_win ~ ., family = "binomial", data = select(train, -game_id, -tm1pPIM, -tm2pPIM, -tm1, -tm2, -yr))
mod_with_phys <- glm(tm1_win ~ ., family = "binomial", data = select(train, -game_id, -tm1, -tm2, -yr))

summary(mod_with_phys)
```
```{r}
# how does increase in pim increase the win probability at certain points in the game?
preds_phys <- predict(mod_with_phys,train)
train$preds <- preds_phys
train$dPreds = train$preds - lag(train$preds)
#train$dPreds[1] = train$preds[1]
train$tm1_currWin <- (train$tm1_score > train$tm2_score)
train$dPIM <- train$tm1PIM - lag(train$tm1PIM)
#train$dPIM[1] = train$tm1PIM[1]


for(g in unique(train$game_id)) {
    game <- train[train$game_id == g, ]
    train[train$game_id == g, ]$dPreds[1] <- game$preds[1]
    train[train$game_id == g, ]$dPIM[1] <- game$tm1PIM[1]
}
```
```{r}
train$goal_diff <- train$tm1_score - train$tm2_score

first_per <- train[train$time <= 1200,]
second_per <- train[train$time > 1200 & train$time <= 2400,]
third_per <- train[train$time > 2400 & train$time <= 3600,]

fights <- na.omit(train[train$dPIM >= 5 & train$dPIM < 10 & train$time <= 3600,])

ggplot(fights) + geom_point(aes(x=time, y=dPreds, color=goal_diff)) + theme_bw() + labs(title = "Effects of Major Penalties on Win Probability", x = "Time", y = "Difference in Probability", color = "Current Goal Diff") + scale_color_gradient2(midpoint = 0, low = "skyblue3", mid = "lightgray",high = "tomato2", space = "Lab" )

ggplot(first_per) + geom_point(aes(x=dPIM, y=dPreds, color=tm1_currWin)) + theme_minimal() + ggtitle("First Period Change in Win Probability Based on PIM") + ylab("Difference in Probability") + xlab("Difference in PIM")

ggplot(second_per) + geom_point(aes(x=dPIM, y=dPreds, color=tm1_currWin)) + theme_minimal() + ggtitle("Second Period Change in Win Probability Based on PIM") + ylab("Difference in Probability") + xlab("Difference in PIM")
```

```{r}
# what happens when the other team didn't score on the PK
all_games$dPIM1 <- all_games$tm1PIM - lag(all_games$tm1PIM)
all_games$dPIM2 <- all_games$tm2PIM - lag(all_games$tm2PIM)

all_games$dpPIM1 <- all_games$tm1pPIM - lag(all_games$tm1pPIM)
all_games$dpPIM2 <- all_games$tm2pPIM - lag(all_games$tm2pPIM)

all_games$dScore1 <- all_games$tm1_score - lag(all_games$tm1_score)
all_games$dScore2 <- all_games$tm2_score - lag(all_games$tm2_score)

for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    all_games[all_games$game_id == g, ]$dPIM1[1] <- game$tm1PIM[1]
    all_games[all_games$game_id == g, ]$dPIM2[1] <- game$tm2PIM[1]
    
    all_games[all_games$game_id == g, ]$dpPIM1[1] <- game$tm1pPIM[1]
    all_games[all_games$game_id == g, ]$dpPIM2[1] <- game$tm2pPIM[1]
    
    all_games[all_games$game_id == g, ]$dScore1[1] <- game$tm1_score[1]
    all_games[all_games$game_id == g, ]$dScore2[1] <- game$tm2_score[1]
}

```
```{r}
all_games$time <- 3600 - all_games$timeLeft
disc_time <- all_games %>% group_by(game_id, time)
score_on_pp <- c()
pim_team_won <- c()

for(g in unique(disc_time$game_id)) {
    game <- disc_time[disc_time$game_id == g, ]
    for(r in c(1:nrow(game))) {
      row <- game[r,]
      if(row$dpPIM1 > row$dpPIM2 & row$dpPIM1 < 5) {
          search_time_diff <- row$dpPIM1 * 60
          pk_time <- disc_time[disc_time$time > row$time & disc_time$time <= (row$time + search_time_diff),]
          pp <- as.numeric(1 %in% pk_time$dScore2)
          pim_team_won <- c(pim_team_won,row$tm1_win)
      } else if(row$dpPIM2 > row$dpPIM1 & row$dpPIM2 < 5) {
        search_time_diff <- row$dpPIM2 * 60
          pk_time <- disc_time[disc_time$time > row$time & disc_time$time <= (row$time + search_time_diff),]
          pp <- as.numeric(1 %in% pk_time$dScore1)
          pim_team_won <- c(pim_team_won,(1-row$tm1_win))
      } else {
        pp <- -1
        pim_team_won <- c(pim_team_won,-1)
      }
      score_on_pp <- c(score_on_pp, pp)
      
    }
}

disc_time$score_pp <- score_on_pp
disc_time



```
```{r}
disc_time$pen_win <- pim_team_won
pens <- disc_time[disc_time$score_pp != -1,]
pens
mean(pens[pens$score_pp == 1,]$pen_win)
mean(pens[pens$score_pp == 0,]$pen_win)
t.test(pens[pens$score_pp == 1,]$pen_win, pens[pens$score_pp == 0,]$pen_win)
```

```{r}
not_pim <- subset(all_games, select = -c(tm1PIM, tm2PIM))

#gameIds_less <- unique(not_pim$game_id)

#train_games_less <- sample(gameIds_less, 0.8 * length(gameIds_less)) ## select 400 games for our training set

train_less <- subset(train, select = -c(tm1PIM, tm2PIM, tm1pPIM, tm2pPIM))

test_less <- subset(test, select = -c(tm1PIM, tm2PIM, tm1pPIM, tm2pPIM))

mod2 <- glm(tm1_win ~ ., family = "binomial", data = select(train_less, -game_id, -tm1, -tm2, -yr))

summary(mod2)
```
```{r}
test_game_df <- all_games %>% 
  filter(!game_id %in% train_games)

test_game_1 <- test_game_df$game_id[2]
game_to_plot <- test_game_df[test_game_df$game_id == "2011010004",]


print(game_to_plot)
to_plot <- subset(game_to_plot, select = -c(game_id, tm1_win))

test_game_df_3 <- to_plot %>% group_by(time) %>%
  summarise(across(c(tm1PIM, tm2PIM, tm1_score, tm2_score), sum))

to_plot_2 <- subset(game_to_plot, select = -c(game_id, tm1_win, tm1PIM, tm2PIM))

game_with_noPIM <- to_plot
game_with_noPIM$tm1PIM <- rep(0, nrow(game_with_noPIM))  # only first team has no pim!

probs_1 <- predict(mod, to_plot, type = "response")
probs_2 <- predict(mod2, to_plot_2, type="response")
probs_3 <- predict(mod, game_with_noPIM, type = "response")
probs_4 <- predict(mod, test_game_df_3, type="response")
plot_df_4 <- data.frame(test_game_df_3$gameTime, probs_4)
colnames(plot_df_4) <- c("gameTime", "probs")
print(plot_df_4)

all_plot <- data.frame(game_to_plot$time, probs_1, probs_2, probs_3)
colnames(all_plot) <- c("gameTime", "probsWithPIM", "probsWOPIM", "probsNoPIM")
new_col <- c()
for(r in c(1:nrow(all_plot))) {
  #print(r)
  row <- all_plot[r,]
  new_col<-c(new_col, plot_df_4[plot_df_4$time == row$gameTime,]$probs)
}

all_plot$probs_4 <- new_col



ggplot(all_plot, aes(x=gameTime)) + geom_point(aes(y=probsWithPIM), color="tomato3", size=0.75) + geom_line(aes(y=probsWithPIM), color="tomato3") + geom_point(aes(y=probsWOPIM), size=0.75) +geom_line(aes(y=probsWOPIM)) + ggtitle("Win Probability of Two Models Game 2011010004") + geom_point(aes(y=probsNoPIM), color="skyblue3", size=0.75) + geom_line(aes(y=probsNoPIM), color="skyblue3") + theme_minimal() #+ geom_point(aes(y=probs_4), color="purple", size=0.75) + geom_line(aes(y=probs_4), color="purple") 

#+ geom_line(aes(y=probsNoPIM), color="purple"")
#+ geom_vline(xintercept=45, linetype="dashed", size=0.25) +  geom_vline(xintercept=228, linetype="dashed", size=0.25) + geom_vline(xintercept=306, linetype="dashed", size=0.25, color="red") + geom_vline(xintercept=1495, linetype="dashed", size=0.25) + geom_vline(xintercept=1758, linetype="dashed", size=0.25)+ geom_point(aes(y=probsNoPIM), color="blue", size=0.75) + geom_line(aes(y=probsNoPIM), color="blue")
print(all_plot)
print(game_to_plot$game_id)
```
```{r}
print(test_game_df)
indx <- c()
for(r in 1:nrow(test_game_df)) {
  row = test_game_df[r,]
  if(r == 1) {
    next
  }
  prev_r <- r-1
  prev_row <- test_game_df[prev_r,]
  #print(prev_row)
  if(row$tm1PIM == prev_row$tm1PIM & row$tm2PIM == prev_row$tm2PIM) {
    indx <- c(indx, r)
  }
}

print(indx)
test_game_df_2 <- test_game_df[-indx,]
test_game_df_2
```
```{r}
all_szns$SVPIM <- all_szns$`PIM/G` * all_szns$GP * all_szns$`SV%`
ggplot(all_szns, aes(x=SVPIM, y=Rk)) + geom_point()
```
```{r}
#PCA
to_pca <- select(all_szns, -c(Tm, Season))
pca_norm <- scale(to_pca)
pca_analysis <- princomp(pca_norm)
summary(pca_analysis)
pca_analysis$loadings[, 1:16]
```
```{r}
all_szns$PIM <- all_szns$`PIM/G` * all_szns$GP
train_data <- subset(all_szns, select = -c(Tm, L, OL, PTS, SOL, GP, SOW, `PTS%`, Season))
#train_data$SVPIM <- train_data$PIM * train_data$`SV%`
#train_data$SVPIM2 <- (train_data$PIM/mean(train_data$PIM)) + train_data$`SV%`
train_data$sPIM <- sqrt(train_data$PIM)

lmod_all <-  lm(W ~ ., data = select(train_data, -c(Rk)))
summary(lmod_all)

lmod_ga <- lm(`GA/G` ~. , data = select(train_data, -c(W, Rk, sPIM)))
summary(lmod_ga)

lmod_gf <- lm(`GF/G` ~. , data = select(train_data, -c(W, Rk, sPIM)))
summary(lmod_gf)

lmod_rk <- lm(Rk ~ . , data = select(train_data, -c(W, SRS, SOS)))
summary(lmod_rk)

cor(train_data)
```
```{r} 
# getting the mean for winners and losers
get_mean <- function(games_df, win) {
  output <- c()
  count <- 0
  for(g in unique(games_df$game_id)) {
    game <- games_df[games_df$game_id == g, ]
    final_row <- game[nrow(game),]
    if(win == 2){
      if(final_row$tm1_win == win) {
        output <- c(output, (final_row$tm1PIM - final_row$tm2PIM))
      } else {
        output <- c(output, (final_row$tm2PIM - final_row$tm1PIM))
      }
    } else {
      if(final_row$tm1_win == win) {
        output <- c(output, final_row$tm1PIM)
      } else {
        output <- c(output,final_row$tm2PIM)
      }
    }
    count <- count + 1
  }
  retVal <- output
  return(retVal)
}

win_pim <- get_mean(all_games, 1.0)
lose_pim <- get_mean(all_games, 0.0)
diff_pim <- get_mean(all_games, 2.0)

win_mean <- mean(win_pim)
lose_mean <- mean(lose_pim)
diff_mean <- mean(diff_pim)
print(sprintf("Winners' mean PIM: %s, losers' mean PIM: %s, mean diff: %s", win_mean, lose_mean, diff_mean))
t.test(win_pim, lose_pim)
```
Are more penalties committed by a team that is already winning?
-> graph of score_diff and average number of penalties committed while in that score diff
```{r}
count2 <- 0
pims_acquired <- c()
goal_diff <- c()
for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    old_tm1_goal_diff <- 0
    old_tm2_goal_diff <- 0
    
    tm1_pims <- 0
    tm2_pims <- 0
    old_tm1_pim <- 0
    old_tm2_pim <- 0
    for(r in c(1:nrow(game))) {
      play <- game[r,]
      #print(play$tm1_score)
      #print(play$tm2_score)
      tm1_goal_diff <- as.numeric(play$tm1_score) - as.numeric(play$tm2_score)
      tm2_goal_diff <- play$tm2_score - play$tm1_score
      
      tm1_pim <- play$tm1PIM
      tm2_pim <- play$tm2PIM
      
      
      if(tm1_goal_diff != old_tm1_goal_diff | tm2_goal_diff != old_tm2_goal_diff) {
        goal_diff <- c(goal_diff,old_tm1_goal_diff)
        pims_acquired <- c(pims_acquired, tm1_pims)
        
        goal_diff <- c(goal_diff,old_tm2_goal_diff)
        pims_acquired <- c(pims_acquired, tm2_pims)
        
        tm1_pims <- 0
        tm2_pims <- 0
        count2 <- count2 + 1
      } else { # this means a new penalty was committed
        if(tm1_pim > old_tm1_pim) {
          tm1_pims <- tm1_pims + (tm1_pim - old_tm1_pim)
        } else {
          tm2_pims <- tm2_pims + (tm2_pim - old_tm2_pim)
        }
      }
      
      old_tm1_goal_diff <- tm1_goal_diff
      old_tm2_goal_diff <- tm2_goal_diff
      
      old_tm1_pim <- tm1_pim
      old_tm2_pim <- tm2_pim
    }
}


#diff_vs_pims <- data.frame(goal_diff, pims_acquired)

```
```{r}
diff_vs_pims <- data.frame(goal_diff, pims_acquired)
diff_vs_pims
to_graph <- diff_vs_pims %>% group_by(goal_diff) %>%
  summarise(across(c(pims_acquired), mean))
ggplot(to_graph, aes(x=goal_diff)) + geom_point(aes(y=pims_acquired), color="purple", size=0.75) + geom_line(aes(y=pims_acquired), color="purple") + theme_minimal()
```
```{r}
plot_data <- diff_vs_pims %>%
  group_by(goal_diff) %>%
  summarise(
    mean_pims = mean(pims_acquired),
    se = sd(pims_acquired) / sqrt(n()),
    n = n()
  )

# Create the plot
plot_data <- plot_data[plot_data$goal_diff > min(plot_data$goal_diff) & plot_data$goal_diff < max(plot_data$goal_diff), ] 
ggplot(plot_data, aes(x = goal_diff, y = mean_pims)) +
  geom_ribbon(aes(ymin = mean_pims - se, ymax = mean_pims + se), 
              alpha = 0.2, fill = "skyblue") +
  geom_line(color = "skyblue3") +
  geom_point(color = "skyblue3") +
  theme_bw() +
  labs(
    title = "Mean Penalty Minutes by Goal Differential",
    x = "Goal Differential",
    y = "Mean Penalty Minutes",
    caption = paste("Error bands represent ±1 standard error")
  ) 
```
```{r}
pop1 <- diff_vs_pims[diff_vs_pims$goal_diff > 0,]
pop2 <- diff_vs_pims[diff_vs_pims$goal_diff < 0,]
t.test(pop1$pims_acquired, pop2$pims_acquired)
```
```{r} 
# get difference added in pim diff over this time

count2 <- 0
pims_acquired <- c()
goal_diff <- c()
for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    old_tm1_goal_diff <- 0
    old_tm2_goal_diff <- 0
    
    tm1_pims <- 0
    tm2_pims <- 0
    old_tm1_pim <- 0
    old_tm2_pim <- 0
    for(r in c(1:nrow(game))) {
      play <- game[r,]
      tm1_goal_diff <- play$tm1_score - play$tm2_score
      tm2_goal_diff <- play$tm2_score - play$tm1_score
      
      tm1_pim <- play$tm1PIM
      tm2_pim <- play$tm2PIM
      
      
      if(tm1_goal_diff != old_tm1_goal_diff | tm2_goal_diff != old_tm2_goal_diff) {
        goal_diff <- c(goal_diff,old_tm1_goal_diff)
        pims_acquired <- c(pims_acquired, (tm1_pims-tm2_pims))
        
        goal_diff <- c(goal_diff,old_tm2_goal_diff)
        pims_acquired <- c(pims_acquired, (tm2_pims-tm1_pims))
        
        tm1_pims <- 0
        tm2_pims <- 0
        count2 <- count2 + 1
      } else { # this means a new penalty was committed
        if(tm1_pim != old_tm1_pim) {
          tm1_pims <- tm1_pims + (tm1_pim - old_tm1_pim)
        } else {
          tm2_pims <- tm2_pims + (tm2_pim - old_tm2_pim)
        }
      }
      
      old_tm1_goal_diff <- tm1_goal_diff
      old_tm2_goal_diff <- tm2_goal_diff
      
      old_tm1_pim <- tm1_pim
      old_tm2_pim <- tm2_pim
    }
}
 
diff_vs_pims2 <- data.frame(goal_diff, pims_acquired)

plot_data2 <- diff_vs_pims2 %>%
  group_by(goal_diff) %>%
  summarise(
    mean_pims = mean(pims_acquired),
    se = sd(pims_acquired) / sqrt(n()),
    n = n()
  )

# Create the plot
ggplot(plot_data2, aes(x = goal_diff, y = mean_pims)) +
  geom_ribbon(aes(ymin = mean_pims - se, ymax = mean_pims + se), 
              alpha = 0.2, fill = "yellowgreen") +
  geom_line(color = "yellowgreen") +
  geom_point(color = "yellowgreen") +
  theme_minimal() +
  labs(
    title = "Change in Penalties in Minutes by Goal Differential",
    x = "Goal Differential",
    y = "Mean Penalty Minutes Gained",
    caption = paste("Error bands represent ±1 standard error")
  ) +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.minor = element_blank()
  )

```
```{r}


```
```{r} 
#let's see if penalties keep a winning team winning
pims_acquired <- c()
goal_diff <- c()
curr_team <- 0
scored_next <- c()
for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    old_tm1_goal_diff <- 0
    old_tm2_goal_diff <- 0
    
    tm1_pims <- 0
    tm2_pims <- 0
    old_tm1_pim <- 0
    old_tm2_pim <- 0
    for(r in c(1:nrow(game))) {
      play <- game[r,]
      tm1_goal_diff <- play$tm1_score - play$tm2_score
      tm2_goal_diff <- play$tm2_score - play$tm1_score
      
      tm1_pim <- play$tm1PIM
      tm2_pim <- play$tm2PIM
      
      if(tm1_goal_diff > old_tm1_goal_diff | tm2_goal_diff > old_tm2_goal_diff) {
         goal_diff <- c(goal_diff,old_tm1_goal_diff)
        pims_acquired <- c(pims_acquired, (tm1_pims-tm2_pims))
        
        goal_diff <- c(goal_diff,old_tm2_goal_diff)
        pims_acquired <- c(pims_acquired, (tm2_pims-tm1_pims))
        tm1_pims <- 0
        tm2_pims <- 0
        count2 <- count2 + 1
      
      }
    
      if(tm1_goal_diff > old_tm1_goal_diff) {
        if(curr_team == 1) {
          scored_next <- c(scored_next, 1)
        } else {
          scored_next <- c(scored_next, 0)
        }
        curr_team <- 1
        
      } else if(tm2_goal_diff > old_tm2_goal_diff) { # someone scored!
        if(curr_team == 1) {
          scored_next <- c(scored_next, 0)
        } else {
          scored_next <- c(scored_next, 1)
        }
        curr_team <- 2
  
      } else { # this means a new penalty was committed
        if(tm1_pim != old_tm1_pim) {
          tm1_pims <- tm1_pims + (tm1_pim - old_tm1_pim)
        } else {
          tm2_pims <- tm2_pims + (tm2_pim - old_tm2_pim)
        }
      }
      
      old_tm1_goal_diff <- tm1_goal_diff
      old_tm2_goal_diff <- tm2_goal_diff
      
      old_tm1_pim <- tm1_pim
      old_tm2_pim <- tm2_pim
    }
}

diff_vs_pims3 <- data.frame(goal_diff, pims_acquired, scored_next)

```
```{r}
curr_winning <- diff_vs_pims3[diff_vs_pims3$goal_diff > 0, ]
ggplot(curr_winning, aes(x=goal_diff, y=pims_acquired, color = scored_next)) + geom_point()+ scale_fill_viridis_c()
```
```{r}
scored_next_graph <- diff_vs_pims3[diff_vs_pims3$scored_next == 0, ]
mean(winning_by_1$pims_acquired)
```
```{r}
train_log <- data.frame(diff_vs_pims3$goal_diff, diff_vs_pims3$pims_acquired)
logistic_model <- glm(scored_next ~ ., family = binomial(), diff_vs_pims3)
summary(logistic_model)
```
```{r}
summed_diffpim <- diff_vs_pims3 %>%
  group_by(pims_acquired) %>%
  summarise(
    mean_scored_next = mean(scored_next))

summed_diffpimW <- diff_vs_pims3[diff_vs_pims3$goal_diff > 0,] %>%
  group_by(pims_acquired) %>%
  summarise(
    mean_scored_next = mean(scored_next))

logistic_modelW <- glm(scored_next ~ ., family = binomial(), diff_vs_pims3[diff_vs_pims3$goal_diff > 0,])
print(summary(logistic_modelW))

logistic_modelL <- glm(scored_next ~ ., family = binomial(), diff_vs_pims3[diff_vs_pims3$goal_diff < 0,])
print(summary(logistic_modelL))

ggplot(summed_diffpimW, aes(x=pims_acquired, y=mean_scored_next)) + geom_point()

  
```
```{r}
losing_scored_next <- diff_vs_pims3[diff_vs_pims3$goal_diff < 0 & diff_vs_pims3$scored_next == 1,]
print(mean(losing_scored_next$pims_acquired))
```
```{r}
# do teams who were losing at one point commit more or less physical penalties than the other?
#let's see if penalties keep a winning team winning
pims_acquired <- c()
goal_diff <- c()
curr_team <- 0
scored_next <- c()
tm1_won <- c()

for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    old_tm1_goal_diff <- 0
    old_tm2_goal_diff <- 0
    
    tm1_pims <- 0
    tm2_pims <- 0
    old_tm1_pim <- 0
    old_tm2_pim <- 0
    for(r in c(1:nrow(game))) {
      play <- game[r,]
      tm1_goal_diff <- play$tm1_score - play$tm2_score
      tm2_goal_diff <- play$tm2_score - play$tm1_score
      
      tm1_pim <- play$tm1pPIM
      tm2_pim <- play$tm2pPIM
      
      if(tm1_goal_diff > old_tm1_goal_diff | tm2_goal_diff > old_tm2_goal_diff) {
         goal_diff <- c(goal_diff,old_tm1_goal_diff)
        pims_acquired <- c(pims_acquired, (tm1_pims-tm2_pims))
        tm1_won <- c(tm1_won, play$tm1_win)
        
        tm1_pims <- 0
        tm2_pims <- 0
        count2 <- count2 + 1
      
      }  else { # this means a new penalty was committed
        if(tm1_pim != old_tm1_pim) {
          tm1_pims <- tm1_pims + (tm1_pim - old_tm1_pim)
        } else {
          tm2_pims <- tm2_pims + (tm2_pim - old_tm2_pim)
        }
      }
      
      old_tm1_goal_diff <- tm1_goal_diff
      old_tm2_goal_diff <- tm2_goal_diff
      
      old_tm1_pim <- tm1_pim
      old_tm2_pim <- tm2_pim
    }
}

dvp_win <- data.frame(goal_diff, pims_acquired, tm1_won)
```
```{r}
dvp_comeback <- dvp_win[dvp_win$goal_diff < 0 & dvp_win$goal_diff > -3 & dvp_win$tm1_won ==1, ]
dvp_no_comeback <- dvp_win[dvp_win$goal_diff < 0 & dvp_win$goal_diff > -3 & dvp_win$tm1_won == 0, ]
mean(dvp_comeback$pims_acquired)
mean(dvp_no_comeback$pims_acquired)
t.test(dvp_comeback$pims_acquired, dvp_no_comeback$pims_acquired)
```
```{r}
dvp_eq1 <- dvp_win[dvp_win$goal_diff ==0 & dvp_win$tm1_won == 1, ]
dvp_eq0 <- dvp_win[dvp_win$goal_diff ==0 & dvp_win$tm1_won == 0, ]
mean(dvp_eq1$pims_acquired)
mean(dvp_eq0$pims_acquired)
t.test(dvp_eq1$pims_acquired, dvp_eq0$pims_acquired)

```
```{r}
dvp_fb <- dvp_win[dvp_win$goal_diff > 0 & dvp_win$goal_diff < 3 & dvp_win$tm1_won == 0, ]
dvp_no_fb <- dvp_win[dvp_win$goal_diff > 0 & dvp_win$goal_diff < 3 & dvp_win$tm1_won == 1, ]
mean(dvp_fb$pims_acquired)
mean(dvp_no_fb$pims_acquired)
t.test(dvp_fb$pims_acquired, dvp_no_fb$pims_acquired)
```
```{r}
dvp_crazy <- dvp_win[dvp_win$goal_diff < -3  & dvp_win$tm1_won == 0, ]
dvp_crazy_2 <- dvp_win[dvp_win$goal_diff < -3 & dvp_win$tm1_won == 1, ]

mean(dvp_crazy$pims_acquired)
mean(dvp_crazy_2$pims_acquired)
t.test(dvp_crazy$pims_acquired, dvp_crazy_2$pims_acquired)
```
```{r}
# memoryless win probability
data_mem <- all_games
gameIds <- unique(all_games$game_id)

mem_tls1 <- c()
mem_tls2 <- c()
mem_ptls1 <- c()
mem_ptls2 <- c()
count <- 0
for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]
    first_period <- game[game$timeLeft >= 2400,]
    second_period <- game[game$timeLeft < 2400 & game$timeLeft >= 1200, ]
    for(r in c(1:nrow(game))) {
      play <- game[r,]

      # get just pim for this period
      if(play$timeLeft < 1200) {
        if(nrow(second_period) == 0) {
          
          if(nrow(first_period) == 0) {
            mem_tl1 <- play$tm1PIM
            mem_tl2 <- play$tm2PIM
            mem_ptl1 <- play$tm1pPIM
            mem_ptl2 <- play$tm2pPIM
            
          } else {
            mem_tl1 <- play$tm1PIM - first_period$tm1PIM[nrow(first_period)]
            mem_tl2 <- play$tm2PIM - first_period$tm2PIM[nrow(first_period)]
            mem_ptl1 <- play$tm1pPIM - first_period$tm1pPIM[nrow(first_period)]
            mem_ptl2 <- play$tm2pPIM - first_period$tm2pPIM[nrow(first_period)]
          }
        } else {
          mem_tl1 <- play$tm1PIM - second_period$tm1PIM[nrow(second_period)]
          mem_tl2 <- play$tm2PIM - second_period$tm2PIM[nrow(second_period)]
          mem_ptl1 <- play$tm1pPIM - second_period$tm1pPIM[nrow(second_period)]
          mem_ptl2 <- play$tm2pPIM - second_period$tm2pPIM[nrow(second_period)]
        }
        
      } else if(play$timeLeft < 2400) {
        
        if(nrow(first_period) == 0) {
          mem_tl1 <- play$tm1PIM
          mem_tl2 <- play$tm2PIM
          mem_ptl1 <- play$tm1pPIM
          mem_ptl2 <- play$tm2pPIM
        } else {
          mem_tl1 <- play$tm1PIM - first_period$tm1PIM[nrow(first_period)]
          mem_tl2 <- play$tm2PIM - first_period$tm2PIM[nrow(first_period)]
          mem_ptl1 <- play$tm1pPIM - first_period$tm1pPIM[nrow(first_period)]
          mem_ptl2 <- play$tm2pPIM - first_period$tm2pPIM[nrow(first_period)]
        }
        
      } else {
        mem_tl1 <- play$tm1PIM
        mem_tl2 <- play$tm2PIM
        
        mem_ptl1 <- play$tm1pPIM
        mem_ptl2 <- play$tm2pPIM
      }

      #print(sprintf("adding %s", mem_tl1))
      mem_tls1 <- c(mem_tls1, mem_tl1)
      mem_tls2 <- c(mem_tls2, mem_tl2)
      mem_ptls1 <- c(mem_ptls1, mem_ptl1)
      mem_ptls2 <- c(mem_ptls2, mem_ptl2)
    }
}

data_mem$tm1PIMIP <- mem_tls1
data_mem$tm2PIMIP <- mem_tls2

data_mem$tm1pPIMIP <- mem_ptls1
data_mem$tm2pPIMIP <- mem_ptls2
tg_mem <- sample(gameIds, 0.8 * length(gameIds)) ## select 400 games for our training set

train_mem <- data_mem %>% 
  filter(game_id %in% tg_mem) 

test_mem <- data_mem %>% 
  filter(!game_id %in% tg_mem) 



```

```{r}
test_mem$tm1pPIMIP
```

```{r}
mod_m2 <- glm(tm1_win ~ ., family = "binomial", data = select(train_mem, -game_id, -tm1, -tm2))

mod_m1 <- glm(tm1_win ~ ., family = "binomial", data = select(train_mem, -game_id, -tm1PIM, -tm2PIM, -tm1, -tm2, -tm1pPIM, -tm2pPIM))
mod_m3 <- glm(tm1_win ~ ., family = "binomial", data = select(train_mem, -game_id, -tm1pPIM, -tm2pPIM, -tm1, -tm2))


summary(mod_m1)
summary(mod2)
```
```{r}
# testing memoryless vs. regular
test_mem$probs_m1 <- predict(mod_m1, subset(test_mem, select = -c(game_id, tm1_win)), type = "response")
test_mem$probs_m2 <- predict(mod_m2, subset(test_mem, select = -c(game_id, tm1_win)), type = "response")
test_mem$probs_noPIM <- predict(mod2, subset(test_mem, select = -c(game_id, tm1_win, tm1_PIM, tm2_PIM, tm1_pPIM, tm2_pPIM)), type = "response")

times_to_test <- c(3000, 2400, 1800, 1200, 600)
times_mem <- c()
outcome <- c()
preds_1 <- c()
preds_2 <- c()
preds_noPIM <- c()
res_1s <- c()
res_2s <- c()
res_noPIMs <- c()
for(g in unique(test_mem$game_id)) {
  game <- test_mem[test_mem$game_id == g,]
  
  for(t in times_to_test) {
    most_recent <- game[game$timeLeft > t,]
    recent_row <- most_recent[nrow(most_recent),]
    if(nrow(most_recent) == 0) {
      next
    }
    
    if(recent_row$probs_m1 > 0.5) {
      preds_1 <- c(preds_1, 1)
      res_1 <- game[1,]$tm1_win == 1
    } else {
      preds_1 <- c(preds_1, 0)
      res_1 <- game[1,]$tm1_win == 0
    }
  
    if(recent_row$probs_m2 > 0.5) {
      preds_2 <- c(preds_2, 1)
      res_2 <- game[1,]$tm1_win == 1
    } else {
      preds_2<- c(preds_2, 0)
      res_2 <- game[1,]$tm1_win == 0
    }
    
    if(recent_row$probs_noPIM > 0.5) {
      preds_noPIM <- c(preds_noPIM, 1)
      res_noPIM <- game[1,]$tm1_win == 1
    } else {
      preds_noPIM <- c(preds_noPIM, 0)
      res_noPIM <- game[1,]$tm1_win == 0
    }
    #print(as.numeric(res_2))
    #print(as.numeric(res_noPIM))
    times_mem <- c(times_mem, t)
    outcome <- c(outcome, game[1,]$tm1_win)
    res_1s <- c(res_1s, as.numeric(res_1))
    res_2s <- c(res_2s, as.numeric(res_2))
    res_noPIMs <- c(res_noPIMs, as.numeric(res_noPIM))
  }
}

results_mem <- data.frame(outcome, preds_1, preds_2, times_mem, res_1s, res_2s, res_noPIMs)
res_per_time <- results_mem %>%
  group_by(times_mem) %>%
  summarise(
    mn1 = mean(res_1s),
    se1 = sd(res_1s) / sqrt(n()),
    n = n(),
    mn2 = mean(res_2s), 
    se2 = sd(res_2s) / sqrt(n()),
    mnnoPIM = mean(res_noPIMs),
    senoPIM = sd(res_noPIMs) / sqrt(n()),
  )

incorrect_1 <- results_mem[results_mem$outcome != results_mem$preds_1,]
incorrect_2 <- results_mem[results_mem$outcome != results_mem$preds_2,]
res_1 <- nrow(incorrect_1) / nrow(results_mem)
res_2 <- nrow(incorrect_2) / nrow(results_mem)
print(sprintf("Result 1(Memoryless only) : %s, Result 2(PIM for whole game): %s", res_1, res_2))
res_per_time
test_mem

res_per_time$timeInGame <- 3600 - res_per_time$times_mem

ggplot(res_per_time, aes(x=timeInGame)) + geom_point(aes(y=mn2), color="tomato3", size=0.75) + geom_line(aes(y=mn2), color="tomato3") + geom_ribbon(aes(ymin = mn1 - se1, ymax = mn1 + se1), 
              alpha = 0.2, fill = "tomato3") + theme_minimal() + geom_point(aes(y=mnnoPIM), color="skyblue", size=0.75) + geom_line(aes(y=mnnoPIM), color="skyblue") + geom_ribbon(aes(ymin = mnnoPIM - senoPIM, ymax = mnnoPIM + senoPIM), 
              alpha = 0.2, fill = "skyblue") + ggtitle("Accuracy in Estimated Win Probability Throughout Game")
ggplot(res_per_time, aes(x=timeInGame)) + geom_point(aes(y=mn2), color="yellowgreen", size=0.75) + geom_line(aes(y=mn2), color="yellowgreen") + geom_ribbon(aes(ymin = mn2 - se2, ymax = mn2 + se2), alpha = 0.2, fill = "yellowgreen") + theme_minimal()
ggplot(res_per_time, aes(x=timeInGame)) + geom_point(aes(y=mnnoPIM), color="skyblue", size=0.75) + geom_line(aes(y=mnnoPIM), color="skyblue") + geom_ribbon(aes(ymin = mnnoPIM - senoPIM, ymax = mnnoPIM + senoPIM), 
              alpha = 0.2, fill = "skyblue") + theme_minimal() 
```
```{r}
get_only_penalties <- function(all_games) {
  count_plays <- 0
  count_pens <- 0
  pen_list <- c()
  for(g in unique(all_games$game_id)) {
    game <- all_games[all_games$game_id == g, ]

    for(r in c(1:nrow(game))) {
      count_plays <- count_plays + 1
      play <- game[r,]
      if(r == 1) {
        if(play$tm1PIM != 0 | play$tm2PIM != 0) {
          pen_list <- c(pen_list, count_plays)
        }
      } else {
        prev_play <- game[r-1,]
        if(play$tm1PIM > prev_play$tm1PIM | play$tm2PIM > prev_play$tm2PIM) {
          pen_list <- c(pen_list, count_plays)
        }
      }
    }
  }
  
  pen_plays <- all_games %>% filter(row_number() %in% pen_list)
  return(pen_plays)
}
penalty_plays <- get_only_penalties(all_games)
```
```{r}
penalty_plays$goal_diff <- penalty_plays$tm1_score - penalty_plays$tm2_score
period_1_pens <- penalty_plays[penalty_plays$time < 1200,]
period_2_pens <- penalty_plays[penalty_plays$time >= 1200 & penalty_plays$time < 2400,]
period_3_pens <- penalty_plays[penalty_plays$time >= 2400,]
```
```{r}
library(dbscan)
# knn model

train_df <- subset(train_df, select = -c(Szn,tmAbbrev, PlayerId, Pos, shootsCatches))


prep_obj <- preProcess(train_df, method = c('center', 'scale'))
trainTransformed <- predict(prep_obj, train_df)
#testTransformed <- predict(prep_obj, test)

# Find optimal k using elbow method
wss <- numeric(10)
for (k in 1:10) {
    km <- kmeans(trainTransformed, centers=k)
    wss[k] <- km$tot.withinss
}

# Plot elbow curve
elbow_data <- data.frame(k = 1:10, wss = wss)
elbow_plot <- ggplot(elbow_data, aes(x=k, y=wss)) +
    geom_line() +
    geom_point() +
    labs(
        title="Elbow Method for Optimal k",
        x="Number of Clusters (k)",
        y="Within-cluster Sum of Squares"
    ) +
    theme_minimal()
print(elbow_plot)

optimal_k <- 3


final_clusters <- kmeans(trainTransformed, centers=optimal_k)


data_with_clusters <- train_df %>%
    mutate(class = as.factor(final_clusters$cluster))


cluster_plot <- ggplot(data_with_clusters, aes(x=Hits, y=SOG, color=class)) +
    geom_point(size=3, alpha=0.6) +
    scale_color_brewer(palette="Set1") +
    labs(
        title="K-means Clustering Results",
        x="X",
        y="Y",
        color="Cluster"
    ) +
    theme_minimal()
print(cluster_plot)


head(data_with_clusters)
```
```{r}

by_team1 <- all_games %>%
  group_by(tm1, yr) %>%
  summarise(
    mean_PIM = mean(tm1PIM),
    se_PIM = sd(tm1PIM),
    n = n(),
    mean_pPIM = mean(tm1pPIM),
    se_pPIM = sd(tm1pPIM),
    wins = sum(tm1_win)
  )

by_team2 <- all_games %>%
  group_by(tm2, yr) %>%
  summarise(
    mean_PIM = mean(tm2PIM),
    se_PIM = sd(tm2PIM),
    n = n(),
    mean_pPIM = mean(tm2pPIM),
    se_pPIM = sd(tm2pPIM),
    wins = n - sum(tm1_win)
  )

ggplot(by_team1, aes(x=se_pPIM, y=wins)) +geom_point()
lmod_df <- subset(by_team1, select=c(-yr, -tm1, -n))
lin_mod_idk <- lm(wins ~ ., data=lmod_df)
summary(lin_mod_idk)
```
```{r}
szns_ranks_df <- standardize_nhl_teams(read_csv("./combined_seasons.csv", show_col_types = FALSE))
#szns_ranks_df$yr <- substring(szns_ranks_df$Season, 1, 4)

rv_colnames <- c("yr", "tmAbbrev", "se_pPIM", "Rk")
rv <- data.frame(matrix(nrow = 0, ncol = length(rv_colnames)))
colnames(rv) <- rv_colnames

se_pPIM <- c()
szns_ranks_df$yr <- substring(szns_ranks_df$Season, 1, 4)
for(r in c(1:nrow(szns_ranks_df))) {
  curr_row <- szns_ranks_df[r,]
  szn_1 <- by_team1[by_team1$yr == curr_row$yr,]
  sel_1 <- szn_1[szn_1$tm1 == unique(curr_row$TmAbbrev)[1],]
  
  szn_2 <- by_team2[by_team2$yr == curr_row$yr,]
  sel_2 <- szn_2[szn_2$tm2 == unique(curr_row$TmAbbrev)[1],]
  to_add <- sqrt(sel_1$se_pPIM^2 + sel_2$se_pPIM^2)
  se_pPIM <- c(se_pPIM, to_add)
  
  if(identical(numeric(0), to_add)) {
    next
  }
  new_row <- list(curr_row$yr, unique(curr_row$TmAbbrev)[1], to_add, curr_row$Rk)
  rv <- rbind(rv, new_row)
}
colnames(rv) <- rv_colnames
rv
ggplot(rv, aes(x=se_pPIM, y=Rk)) + geom_point()
```
```{r}
van_2011_games1 <- all_games[all_games$tm1 == "VAN" & all_games$yr == "2011",]
van_2011_games2 <- all_games[all_games$tm2 == "VAN" & all_games$yr == "2011",]
van_2011_games2
van_tot1 <- van_2011_games1 %>% group_by(game_id) %>% summarise(across(c(tm1PIM, tm1pPIM, tm1_win), sum))
van_tot2 <- van_2011_games2 %>% group_by(game_id) %>% summarise(across(c(tm2PIM, tm2pPIM, tm1_win), sum))
van_tot1$bin <- (van_tot1$tm1_win != 0)
van_tot2$bin <- (van_tot2$tm1_win == 0)

van_cols <- c("game_id", "PIM", "pPIM", "won")
new_rows <- nrow(van_tot1) + nrow(van_tot2)
van_info <- data.frame(matrix(nrow = new_rows, ncol = length(van_cols)))
colnames(van_info) <- van_cols
van_info$game_id <- c(van_tot1$game_id, van_tot2$game_id)
van_info$PIM <- c(van_tot1$tm1PIM, van_tot2$tm2PIM)
van_info$pPIM <- c(van_tot1$tm1pPIM, van_tot2$tm2pPIM)
van_info$won <- c(van_tot1$bin, van_tot2$bin)
van_info
```


```