---
title: "R Notebook"
output: html_notebook
---


```{r, message=FALSE} 
# Installing dependencies...
library(tidyverse)
library(caTools)
library(doParallel)
library(foreach)
library(data.table)

source("data_processing.R")
#source("hockey_game_utils.R")
source("parallel_hockey_utils.R")

unregister_dopar() # get rid of all past clusters, do not want to blow up computer
```
```{r primary_data_collection}
# primary data collection here, DO NOT run if already have data csvs 
do_primary_collection() 
```
```{r}
player_agg_files <- list.files(path = "data_processing", 
                          pattern = "*_player_agg_df.csv",
                          recursive = TRUE,
                          full.names = TRUE)
player_aggs <- read_csv(player_agg_files[1])
for(n in 2:length(player_agg_files)) {
  player_aggs <- rbind(player_aggs, read_csv(player_agg_files[n]))
}
na.omit(player_aggs)
for(i in 1:nrow(player_aggs)) {
  curr_row <- player_aggs[i,]

  if(!is.na(curr_row$TmAbbrev)) {
    if(curr_row$TmAbbrev == "PHX") {
      curr_row$TmAbbrev <- "ARI"
    }
  }
}
tm_aggs <- player_aggs %>% group_by(yr, TmAbbrev) %>%
  summarise(across(c(SOG, Hits, Back, Wrist, Slap, Snap, Tip, Deflected, Missed, Blocked, G), sum))
```
```{r PCA_teams}
only_num <- tm_aggs[c("Hits", "Blocked", "Missed", "Wrist", "Snap", "Back", "Tip", "Slap", "Deflected")]
only_num_scaled <- scale(only_num)
pca <- princomp(only_num_scaled)
summary(pca)
pca$loadings
mod_data <- tm_aggs
mod_data$BackR <- mod_data$Back / mod_data$SOG
mod_data$WristR <- mod_data$Wrist / mod_data$SOG
mod_data$SnapR <- mod_data$Snap / mod_data$SOG
mod_data$SlapR <- mod_data$Slap / mod_data$SOG
mod_data$TipR <- mod_data$Tip / mod_data$SOG
mod <- lm(mod_data$G ~ mod_data$Hits +  mod_data$BackR + mod_data$WristR + mod_data$SnapR + mod_data$TipR + mod_data$SlapR )
summary(mod)
```
```{r PCA}
# PCA on player aggregate statistics, since we collected more reducing dimensionality would be great
only_num <- player_aggs[c("Hits", "Blocked", "Missed", "Wrist", "Snap", "Back", "Tip", "Slap", "Deflected")]
only_num_scaled <- scale(only_num)
pca <- princomp(only_num_scaled)
summary(pca)
pca$loadings
sum(pca$loadings[,1]^2)
```
```{r}
roster_files <- list.files(path = "data_collection/player_data", 
                          pattern = "\\.csv$",
                          recursive = TRUE,
                          full.names = TRUE)

# Read and combine all files, adding year information
complete_roster <- roster_files %>%
  map_df(~{
    # Extract year from the file path
    year <- basename(dirname(.x))
    
    df <- read_csv(.x, show_col_types = FALSE)
    df$year <- year
    return(df)
  }) %>%
  # Reorder columns to put year first
  select(year, everything())

```

```{r}
# get info from csvs stored in primary collection above
yrs <- c("2012")
count <- 0
for(yr in yrs) {
  if(count == 0) {
    big_player_df <- read_csv(sprintf("./%s_df/big_player_df.csv", yr))
    giant_df <- read_csv(sprintf("./%s_df/giant_df.csv", yr))
    big_team_df <- read_csv(sprintf("./%s_df/big_team_df.csv", yr))
  } else {
    big_player_df <- rbind(big_player_df, read_csv(sprintf("./{yr}_df/big_player_df.csv")))
    giant_df <- rbind(giant_df, read_csv(sprintf("./{yr}_df/giant_df.csv")))
    big_team_df <- rbind(big_team_df, read_csv(sprintf("./{yr}_df/big_team_df.csv")))
  }
  count = count + 1
}
```
```{r}
big_player_df
shift_changes <- giant_df[giant_df$type == "shift-change",]
shift_changes[shift_changes$playerIDs %like% "8474037", ]
length(unique(shift_changes$yr))

get_player_profile(giant_df, big_player_df, "8474037")
```
```{r}
library(lubridate)
big_player_df <- player_aggs

#get position and shoots catches
pos <- c()
sc <- c()
bd <- c()
for(r in c(1:nrow(big_player_df))) {
  row <- big_player_df[r,]
  if(is.null(row$PlayerId)) {
    currPos <-"000"
    currsc <- "000"
    currbd <- 0000
  } else{
    szn_check <- sprintf("%s%s", row$yr, (as.numeric(row$yr) + 1))
    selected <- complete_roster[complete_roster$season == szn_check & complete_roster$id == row$PlayerId,]
    currPos <- selected$positionCode[1]
    currsc <- selected$shootsCatches[1]
    currbd <- format(as.Date(selected$birthDate[1], format="%d/%m/%Y"),"%Y")

  }
  pos <- c(pos, currPos)
  sc <- c(sc, currsc)
  bd <- c(bd, currbd)
}
big_player_df$Pos <- pos
big_player_df$shootsCatches <- sc
big_player_df$birthDate <- bd

#player_counts_df <- big_player_df %>% group_by(yr, PlayerId, TmAbbrev, shootsCatches, Pos, birthDate) %>%
  #summarise(across(c(SOG, Wrist, Slap, Snap, Tip, Deflected, Missed, Blocked, Goals, Hits), sum))

  #player_counts_df$birthDate <- as.numeric(player_counts_df$birthDate)
#player_counts_df$Age <- player_counts_df$Szn - player_counts_df$birthDate
#player_counts_df <- player_counts_df[-1,] # !!important!! removes dummy player 000
#player_counts_df
```
```{r PAM_cluster}
library(cluster)
library(factoextra)
library(ggplot2)

player_counts_df <- big_player_df
player_counts_df$Age <- player_counts_df$yr - as.numeric(player_counts_df$birthDate)
player_counts_df <- player_counts_df[player_counts_df$birthDate != 0,]
forwards <- player_counts_df[player_counts_df$Pos == "L" | player_counts_df$Pos == "R" | player_counts_df$Pos == "C",]
forwards <- na.omit(forwards)

selected_columns <- c("forwards.PlayerId", "yr", "G")
#to_train <- data.frame(forwards$Hits)
to_train <- data.frame(forwards$PlayerId)
to_train$yr = forwards$yr
to_train$G <- forwards$G
to_train$BlockR <- forwards$Blocked / forwards$SOG
to_train$MissedR <- forwards$Missed / forwards$SOG
to_train$WristR <- forwards$Wrist / forwards$SOG
to_train$SnapR <- forwards$Snap / forwards$SOG
to_train$TipR <- forwards$Tip / forwards$SOG
to_train$BackR <- forwards$Back / forwards$SOG
to_train$SlapR <- forwards$Slap / forwards$SOG
to_train$DefR <- forwards$Deflected / forwards$SOG
to_train <- na.omit(to_train)
forwards_scale <- data.frame(scale(select(to_train, -selected_columns)))
forwards_scale


fviz_nbclust(forwards_scale, pam, method ="silhouette")+theme_minimal()

#Looks like 2 clusters is the ticket
kmeans_for <- pam(forwards_scale, k = 3)
for_cluster <- factor(kmeans_for$cluster) 
to_train$cluster <- for_cluster
to_train$cluster <- as.numeric(for_cluster)
to_train
```
```{r}
cluster_1 <- to_train[to_train$cluster == 1,]
hist(cluster_1$G)

cluster_2 <- to_train[to_train$cluster == 2,]
summary(cluster_2)
hist(cluster_2$G)

cluster_3<- to_train[to_train$cluster == 3,]
summary(cluster_3)
hist(cluster_3$G)


```
```{r}
summary(cluster_1)
summary(cluster_3)
```
```{r}
summary(cluster_2)
```
```{r}
player_counts_df <- big_player_df
player_counts_df$Age <- player_counts_df$yr - as.numeric(player_counts_df$birthDate)
player_counts_df <- player_counts_df[player_counts_df$birthDate != 0,]
forwards <- player_counts_df[player_counts_df$Pos == "L" | player_counts_df$Pos == "R" | player_counts_df$Pos == "C",]
forwards <- na.omit(forwards)

selected_columns <- c("Hits", "Blocked", "Missed", "Wrist", "Snap", "Back", "Slap", "Deflected")
forwards_scale <- data.frame(scale(forwards[,selected_columns]))

forwards_scale <- na.omit(forwards_scale)
test_df <- data.frame(matrix(ncol = 2, nrow = 10))
colnames(test_df) <- c('k', 'ss')

for(i in 1:10) { 
  k_means <- kmeans(forwards_scale, centers = i, nstart = 20, iter.max=30) 
  ss <- k_means$tot.withinss 
  test_df[i, 'k'] <- i  
  test_df[i, 'ss'] <- ss
}
ggplot(test_df, aes(x=k, y=ss)) + geom_point() + geom_line() + xlab("Clusters") + ylab("Sum of Squares in Cluster") + ggtitle("Sum of Squares per Cluster Size")

#Looks like 5 clusters is the ticket
kmeans_for <- kmeans(forwards_scale, centers = 3, nstart = 20, iter.max=30)
for_cluster <- factor(kmeans_for$cluster) 
forwards_scale$cluster <- for_cluster
forwards$cluster <- as.numeric(for_cluster)
forwards
```
```{r}

```
```{r}
# Let's look at performance of two teams in 2011, see if they have different distributions of clusters
bos <- forwards[forwards$TmAbbrev =="BOS",]
cbj <- forwards[forwards$TmAbbrev =="CBJ",]
bos <- bos[bos$yr == "2011",]
cbj <- cbj[cbj$yr == "2011",]
bos$cluster
cbj$cluster

ggplot(data=bos, aes(cluster)) + geom_bar() + ggtitle("Frequencies of Clusters, BOS 2011")
ggplot(data=cbj, aes(cluster)) + geom_bar() + ggtitle("Frequencies of Clusters, CBJ 2011")


```

```{r}
cluster_1 <- forwards[forwards$cluster == 1,]
summary(cluster_1)
```
```{r PCA_2}
# PCA on player aggregate statistics, since we collected more reducing dimensionality would be great
only_num <- forwards[c("G", "A", "Hits", "Blocked", "Missed", "SOG", "Wrist", "Snap", "Back", "Slap", "Deflected", "cluster")]
only_num_scaled <- scale(only_num)
pca <- princomp(only_num_scaled)
summary(pca)
pca$loadings
```
```{r}

team_counts_df <- big_team_df %>% group_by(Szn, tmAbbrev) %>%
  summarise(across(c(W,L, SOG, Wrist, Slap, Snap, Tip, Deflect, Missed, Blocked, Goals), sum))

team_counts_df$WristP <- team_counts_df$Wrist / team_counts_df$SOG
team_counts_df$SlapP <- team_counts_df$Slap / team_counts_df$SOG
team_counts_df$TipP <- team_counts_df$Tip / team_counts_df$SOG
team_counts_df$SnapP <- team_counts_df$Snap / team_counts_df$SOG

vars_col <- c()
means_col <- c()
for(r in c(1:nrow(team_counts_df))) {
  row <- team_counts_df[r,]
  curr_vars <- sd(c(row$WristP, row$SnapP, row$SlapP, row$TipP))
  vars_col <- c(vars_col, curr_vars)
  
  curr_mean <- (row$Tip + (2*row$Wrist) + (3*row$Snap) + (4*row$Slap)) / (row$Tip + row$Wrist + row$Snap + row$Slap)
  means_col <- c(means_col, curr_mean)
}

team_counts_df$shot_var <- vars_col
team_counts_df$means <- means_col
tot_mean <- mean(team_counts_df$means)
mn_var <- mean(team_counts_df$shot_var)

relMeans <- c()
relMeans2 <- c()
for(r in c(1:nrow(team_counts_df))) {
  row <- team_counts_df[r,]
  curr_mean_diff <- row$means - tot_mean
  relMeans <- c(relMeans, curr_mean_diff)
  
  curr_var_diff <- row$shot_var - mn_var
  relMeans2 <- c(relMeans2, curr_var_diff)
}

team_counts_df$relMean <- relMeans
team_counts_df$relVar <- relMeans2


team_counts_df
```
```{r}

team_counts_df$WP <- team_counts_df$W / (team_counts_df$W + team_counts_df$L)
team_counts_df$SOG.G <- team_counts_df$SOG / (team_counts_df$W + team_counts_df$L)

ggplot(team_counts_df, aes(x=Goals, y=W)) +geom_point() + xlab("Goals") + ylab("Wins")
```
```{r}
winModLin <- lm(team_counts_df$Goals ~ I(team_counts_df$relMean^2) + I(team_counts_df$shot_var^0.5))
summary(winModLin)
```
```{r}
player_goals_df <- player_counts_df[player_counts_df$Goals != 0,]

team_sds_df <- player_goals_df %>% group_by(Szn, tmAbbrev) %>%
  summarise(across(c(SOG, Wrist, Slap, Snap, Tip, Deflect, Missed, Blocked, Goals), sd))


new_col <- c()
new_col_goals <- c()
for(r in c(1:nrow(team_sds_df))) {
  row <- team_sds_df[r,]
  
  new_col <- c(new_col, team_counts_df[team_counts_df$tmAbbrev == row$tmAbbrev,]$W)
  new_col_goals <- c(new_col_goals, team_counts_df[team_counts_df$tmAbbrev == row$tmAbbrev,]$Goals)
}

colnames(team_sds_df) <- c("Szn", "tmAbbrev", "SOG_sd", "Wrist_sd", "Slap_sd", "Snap_sd", "Tip_sd", "Deflect_sd", "Missed_sd", "Blocked_sd", "Goals_sd")
team_sds_df$W <- new_col
team_sds_df$Goals <- new_col_goals
ggplot(team_sds_df, aes(x=Slap_sd, y=Goals)) + geom_point() + xlab("Variance in Number of Slapshots") + ylab("Goals")
```
```{r}
print(select(team_sds_df, -c(Szn, tmAbbrev)))

sd_model <- lm(W ~ Slap_sd + SOG_sd + Wrist_sd +Snap_sd, data=team_sds_df)
summary(sd_model)
```
```{r}
player_counts_df <- na.omit(player_counts_df[-1,])
player_counts_df
```
```{r}
train_df <- player_counts_df[player_counts_df$Pos != "D" & player_counts_df$Pos != "G",]
train_df <- subset(train_df, select = -c(Szn,tmAbbrev, PlayerId, Pos, shootsCatches))
print(train_df)
```
```{r}
library(dbscan)
#trainIndex <- createDataPartition(train_df$SOG, 
								  #times=1, 
								  #p = .8, 
								  #list = FALSE)
#train <- subset(train_df[trainIndex, ], select=-c(PlayerId))
#test <- subset(train_df[-trainIndex, ], select=-c(PlayerId))

# knn model
prep_obj <- preProcess(train_df, method = c('center', 'scale'))
trainTransformed <- predict(prep_obj, train_df)
#testTransformed <- predict(prep_obj, test)

# Find optimal k using elbow method
wss <- numeric(10)
for (k in 1:10) {
    km <- kmeans(trainTransformed, centers=k)
    wss[k] <- km$tot.withinss
}

# Plot elbow curve
elbow_data <- data.frame(k = 1:10, wss = wss)
elbow_plot <- ggplot(elbow_data, aes(x=k, y=wss)) +
    geom_line() +
    geom_point() +
    labs(
        title="Elbow Method for Optimal k",
        x="Number of Clusters (k)",
        y="Within-cluster Sum of Squares"
    ) +
    theme_minimal()
print(elbow_plot)

optimal_k <- 3


final_clusters <- kmeans(trainTransformed, centers=optimal_k)


data_with_clusters <- train_df %>%
    mutate(class = as.factor(final_clusters$cluster))


cluster_plot <- ggplot(data_with_clusters, aes(x=Hits, y=SOG, color=class)) +
    geom_point(size=3, alpha=0.6) +
    scale_color_brewer(palette="Set1") +
    labs(
        title="K-means Clustering Results",
        x="X",
        y="Y",
        color="Cluster"
    ) +
    theme_minimal()
print(cluster_plot)


head(data_with_clusters)
```
```{r}

res_df <- player_counts_df[player_counts_df$Pos != "D" & player_counts_df$Pos != "G",]
res_df$class <- final_clusters$cluster
# let's take a look at Nugent-Hopkins-McDavid-Hyman
nugent_hopkins <- res_df[res_df$PlayerId == "8476454",]
mcdavid <- res_df[res_df$PlayerId == "8478402",]
hyman <- res_df[res_df$PlayerId == "8475786",]
print(nugent_hopkins$class)
```
